language: ruby
cache: bundler
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.1
  - 2.4.0
gemfile:
  - gemfiles/jekyll_3.1.gemfile
  - gemfiles/jekyll_3.gemfile
  - gemfiles/jekyll_2.gemfile
addons:
  code_climate:
    repo_token: 6b81e393ea6ad38560386f650ea2fb0e57a7beb5e20f8c8364fabee30d5bff07
